============================= test session starts ==============================
platform linux -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/runner/work/Assessment-Networking-Week-1-main/Assessment-Networking-Week-1-main
collected 56 items

test_challenge_1.py ..............                                       [ 25%]
test_challenge_2.py .............                                        [ 48%]
test_challenge_3.py FFFFFFFFFFFFFF                                       [ 73%]
test_challenge_4.py FFFFFFFFFFFFFFF                                      [100%]

======================== 29 failed, 27 passed in 13.82s ========================
************* Module storetoise_1
storetoise_1.py:22:0: W0311: Bad indentation. Found 9 spaces, expected 8 (bad-indentation)
storetoise_1.py:27:0: C0303: Trailing whitespace (trailing-whitespace)
storetoise_1.py:76:0: C0304: Final newline missing (missing-final-newline)
storetoise_1.py:14:40: W0621: Redefining name 'number' from outer scope (line 72) (redefined-outer-name)
storetoise_1.py:19:12: W0622: Redefining built-in 'id' (redefined-builtin)
storetoise_1.py:18:7: C0121: Comparison 'number == None' should be 'number is None' (singleton-comparison)
storetoise_1.py:50:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_1.py:50:0: C0103: Function name "get_API_json" doesn't conform to snake_case naming style (invalid-name)
storetoise_1.py:50:17: W0621: Redefining name 'username' from outer scope (line 71) (redefined-outer-name)
storetoise_1.py:51:15: W3101: Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely (missing-timeout)
storetoise_1.py:55:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_1.py:55:18: W0621: Redefining name 'number' from outer scope (line 72) (redefined-outer-name)
storetoise_1.py:56:7: C0121: Comparison 'number != None' should be 'number is not None' (singleton-comparison)
************* Module storetoise_2
storetoise_2.py:22:0: W0311: Bad indentation. Found 9 spaces, expected 8 (bad-indentation)
storetoise_2.py:27:0: C0303: Trailing whitespace (trailing-whitespace)
storetoise_2.py:48:0: C0301: Line too long (113/100) (line-too-long)
storetoise_2.py:50:0: C0301: Line too long (104/100) (line-too-long)
storetoise_2.py:97:0: C0304: Final newline missing (missing-final-newline)
storetoise_2.py:92:4: W0622: Redefining built-in 'id' (redefined-builtin)
storetoise_2.py:14:40: W0621: Redefining name 'number' from outer scope (line 91) (redefined-outer-name)
storetoise_2.py:19:12: W0621: Redefining name 'id' from outer scope (line 92) (redefined-outer-name)
storetoise_2.py:18:7: C0121: Comparison 'number == None' should be 'number is None' (singleton-comparison)
storetoise_2.py:31:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_2.py:31:21: W0621: Redefining name 'username' from outer scope (line 90) (redefined-outer-name)
storetoise_2.py:31:36: W0621: Redefining name 'id' from outer scope (line 92) (redefined-outer-name)
storetoise_2.py:32:15: W3101: Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely (missing-timeout)
storetoise_2.py:41:4: W0702: No exception type(s) specified (bare-except)
storetoise_2.py:39:12: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
storetoise_2.py:57:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_2.py:57:0: C0103: Function name "get_API_json" doesn't conform to snake_case naming style (invalid-name)
storetoise_2.py:57:17: W0621: Redefining name 'username' from outer scope (line 90) (redefined-outer-name)
storetoise_2.py:58:15: W3101: Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely (missing-timeout)
storetoise_2.py:62:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_2.py:62:18: W0621: Redefining name 'number' from outer scope (line 91) (redefined-outer-name)
storetoise_2.py:63:7: C0121: Comparison 'number != None' should be 'number is not None' (singleton-comparison)
storetoise_2.py:75:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_2.py:75:19: W0621: Redefining name 'number' from outer scope (line 91) (redefined-outer-name)
storetoise_2.py:76:7: C0121: Comparison 'number != None' should be 'number is not None' (singleton-comparison)
************* Module storetoise_3
storetoise_3.py:22:0: W0311: Bad indentation. Found 9 spaces, expected 8 (bad-indentation)
storetoise_3.py:27:0: C0303: Trailing whitespace (trailing-whitespace)
storetoise_3.py:48:0: C0301: Line too long (113/100) (line-too-long)
storetoise_3.py:50:0: C0301: Line too long (104/100) (line-too-long)
storetoise_3.py:97:0: C0304: Final newline missing (missing-final-newline)
storetoise_3.py:92:4: W0622: Redefining built-in 'id' (redefined-builtin)
storetoise_3.py:14:40: W0621: Redefining name 'number' from outer scope (line 91) (redefined-outer-name)
storetoise_3.py:19:12: W0621: Redefining name 'id' from outer scope (line 92) (redefined-outer-name)
storetoise_3.py:18:7: C0121: Comparison 'number == None' should be 'number is None' (singleton-comparison)
storetoise_3.py:31:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_3.py:31:21: W0621: Redefining name 'username' from outer scope (line 90) (redefined-outer-name)
storetoise_3.py:31:36: W0621: Redefining name 'id' from outer scope (line 92) (redefined-outer-name)
storetoise_3.py:32:15: W3101: Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely (missing-timeout)
storetoise_3.py:41:4: W0702: No exception type(s) specified (bare-except)
storetoise_3.py:39:12: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
storetoise_3.py:57:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_3.py:57:0: C0103: Function name "get_API_json" doesn't conform to snake_case naming style (invalid-name)
storetoise_3.py:57:17: W0621: Redefining name 'username' from outer scope (line 90) (redefined-outer-name)
storetoise_3.py:58:15: W3101: Missing timeout argument for method 'requests.get' can cause your program to hang indefinitely (missing-timeout)
storetoise_3.py:62:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_3.py:62:18: W0621: Redefining name 'number' from outer scope (line 91) (redefined-outer-name)
storetoise_3.py:63:7: C0121: Comparison 'number != None' should be 'number is not None' (singleton-comparison)
storetoise_3.py:75:0: C0116: Missing function or method docstring (missing-function-docstring)
storetoise_3.py:75:19: W0621: Redefining name 'number' from outer scope (line 91) (redefined-outer-name)
storetoise_3.py:76:7: C0121: Comparison 'number != None' should be 'number is not None' (singleton-comparison)
************* Module storetoise_4
storetoise_4.py:1:0: R0801: Similar lines in 2 files
==storetoise_2:[5:97]
==storetoise_3:[5:97]
BASE_URL = "http://storetoise-lb-992940215.eu-west-2.elb.amazonaws.com"


class APIError(Exception):
    """An error for issues with contacting an API."""



def display_storage_ids(namespace: str, number: str = None) -> None:
    """Prints a list of storage IDs in ascending order based on a namespace given."""
    ids = sorted(get_API_json(namespace)["ids"])
    message = ""
    if number == None:
        for id in ids:
            message += f"{id}\n"
    elif number > len(ids):
         for id in ids:
            message += f"{id}\n"
    else:
        for i in range(number):
            message += f"{ids[i]}\n"

    print(message[:-1])


def display_messages(username: str, id: int) -> None:
    response = requests.get(f'{BASE_URL}/storage/{username}/{id}')
    print(f'{BASE_URL}/storage/:{username}/:{id}')
    try:
        messages = response.json()["messages"]
        if len(messages) == 0:
            print(f'No messages found for storage ID {id}.')
        else:
            for i in range(len(messages)):
                print(f"{i}) {messages[i]}")
    except:
        print("Cannot get messages for a non-existent storage ID.")


def get_arg_parser() -> ArgumentParser:
    """Returns an argument parser object."""

    parser = ArgumentParser(prog="Storetoise CLI", description="A command-line interface to the Storetoise API.")

    parser.add_argument("-u", "--username", help="The username for the namespace to use", required=True)
    parser.add_argument("-n", "--number", help="The number of results to return")
    parser.add_argument("-s", "--storage", help="Displays messages from a given id")

    return parser


def get_API_json(username: str) -> dict:
    response = requests.get(f'{BASE_URL}//storage/:{username}')
    return response.json()


def verify_number(number: str):
    if number != None:
        if not number.isnumeric():
            print("Number must be an integer between 0 and 1000.")
            number = None
        elif float(number) < 0 or float(number) > 1000:
            print("Number must be an integer between 0 and 1000.")
            number = None
        else:
            number = int(number)
    return number


def verify_storage(number: str):
    if number != None:
        if not number.isnumeric():
            print("Storage ID must be a three-digit integer.")
            number = None
        elif len(number) != 3:
            print("Storage ID must be a three-digit integer.")
            number = None
        else:
            number = int(number)
    return number

if __name__ == "__main__":
    args = get_arg_parser().parse_args()
    print(args)
    username = args.username
    number = verify_number(args.number)
    id = verify_storage(args.storage)
    try:
        display_storage_ids(namespace=username, number=number)
        display_messages(username, id)
    except (ValueError, APIError) as e:
        print(str(e)) (duplicate-code)
storetoise_4.py:1:0: R0801: Similar lines in 2 files
==storetoise_1:[5:34]
==storetoise_2:[5:31]
BASE_URL = "http://storetoise-lb-992940215.eu-west-2.elb.amazonaws.com"


class APIError(Exception):
    """An error for issues with contacting an API."""



def display_storage_ids(namespace: str, number: str = None) -> None:
    """Prints a list of storage IDs in ascending order based on a namespace given."""
    ids = sorted(get_API_json(namespace)["ids"])
    message = ""
    if number == None:
        for id in ids:
            message += f"{id}\n"
    elif number > len(ids):
         for id in ids:
            message += f"{id}\n"
    else:
        for i in range(number):
            message += f"{ids[i]}\n"

    print(message[:-1])



def get_arg_parser() -> ArgumentParser:
    """Returns an argument parser object."""
 (duplicate-code)
storetoise_4.py:1:0: R0801: Similar lines in 2 files
==storetoise_1:[46:68]
==storetoise_2:[53:75]
    return parser


def get_API_json(username: str) -> dict:
    response = requests.get(f'{BASE_URL}//storage/:{username}')
    return response.json()


def verify_number(number: str):
    if number != None:
        if not number.isnumeric():
            print("Number must be an integer between 0 and 1000.")
            number = None
        elif float(number) < 0 or float(number) > 1000:
            print("Number must be an integer between 0 and 1000.")
            number = None
        else:
            number = int(number)
    return number


 (duplicate-code)
storetoise_4.py:1:0: R0801: Similar lines in 2 files
==storetoise_1:[61:70]
==storetoise_2:[81:88]
            number = None
        else:
            number = int(number)
    return number



if __name__ == "__main__":
    args = get_arg_parser().parse_args() (duplicate-code)

------------------------------------------------------------------
Your code has been rated at 6.19/10 (previous run: 6.19/10, +0.00)

